# Generated by Django 4.1 on 2022-08-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='dd',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='birthday',
            field=models.DateField(),
        ),
    ]
