# Generated by Django 4.1 on 2022-08-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='dd',
        ),
    ]
