# Generated by Django 4.1 on 2022-08-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contacts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='telephone',
            field=models.CharField(max_length=25),
        ),
    ]
